language: ruby
rvm:
  - 2.4.1

 branches:
 	only:
 	- master

install:
  - bundle install

script: bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false

cache: bundler